### ISSUE TITLE
Crdential with userLabel "initial" leads to unnecessary UPDATE USER

### ISSUE THREAD

**Issue by srose** [adorsys/keycloak-config-cli#882] opened 2023-06-12 06:57 UTC
### Current Behavior

If a user has a credential with userLabel "initial" as the only credential, then this will result in unnecessary updates to the user on re-execution.

Background: Once the user has been created in keycloak, the existing user is retrieved for comparison. Before the comparison, the credential with userLabel "initial" is removed. Thereby the user object from the local configuration has an empty list as credential. The Keycloak API responds with null. The comparison therefore detects a difference and an update is performed again.

### Expected Behavior

Somehow recognise null and empty list as "same".

### Steps To Reproduce

```markdown
1. Definition of a user in yaml/json, containing a credential with userLabel "initial"
2. Run Import
3. Change the file, but not the user definition to make the import logic start again
4. Run Import
5. See UPDATE USER Event for the user not changed.
```

### Environment

- Keycloak Version: 21.1.1
- keycloak-config-cli Version: 5.6.1
- Java Version: 17

### Anything else?

- Some comments/opinions would be great

**Comment by gzm0** [comment] 2023-12-20 08:41
Dupe of #819?

**Closed** 2024-02-01 07:13 UTC
Labels: bug
